- name: Pre-warm SSH connections
  hosts: all
  gather_facts: false
  tasks:
    - name: Ping all hosts to trigger connection & YubiKey touch
      ansible.builtin.ping:

- name: Stop All Docker Containers
  hosts: docker
  become: true
  tasks:
    - name: Stop all running containers
      ansible.builtin.shell: |
        docker ps -q | xargs -r docker rm -f
      args:
        executable: /bin/bash
      changed_when: false
      ignore_errors: true
      # noqa ignore-errors

- name: Install Exporters on Hypervisors
  hosts: proxmox_servers
  roles:
    - prometheus.prometheus.node_exporter
    - prometheus.prometheus.smartctl_exporter

- name: Configure Media Server
  hosts: media_servers
  vars_files:
    - vars/secrets.yml
    - vars/config_vars.yml
  roles:
    - media

- name: Configure Reverse Proxy
  hosts: proxy
  vars_files:
    - vars/secrets.yml
    - vars/config_vars.yml
  roles:
    - proxy

- name: Configure Database Servers
  hosts: db_servers
  vars_files:
    - vars/secrets.yml
  roles:
    - db

- name: Configure VaultWarden
  hosts: vaultwarden
  vars_files:
    - vars/secrets.yml
  roles:
    - vaultwarden

- name: Configure Backup Server
  hosts: backup
  vars_files:
    - vars/secrets.yml
    - vars/config_vars.yml
  roles:
    - backup

- name: Configure NextCloud Server
  hosts: nextcloud
  vars_files:
    - vars/secrets.yml
  roles:
    - nextcloud

- name: Configure Actual Server
  hosts: budget
  roles:
    - budget

- name: Configure Reactive Resume
  hosts: resume
  vars_files:
    - vars/secrets.yml
  roles:
    - resume

- name: Configure Search Server
  hosts: search
  vars_files:
    - vars/secrets.yml
  roles:
    - search

- name: Configure Monitoring Server
  hosts: monitor
  vars_files:
    - vars/secrets.yml
  roles:
    - monitor

- name: Install rsyslog on Non-Docker Hosts
  hosts: all:!docker
  become: true
  tasks:
    - name: Install rsyslog
      ansible.builtin.apt:
        name: rsyslog
        state: present

    - name: Copy rsyslog Config
      ansible.builtin.template:
        src: "templates/rsyslog.conf.j2"
        dest: "/etc/rsyslog.conf"
        force: true
        mode: "0664"
        owner: root
        group: root

    - name: Start and Enable rsyslog
      ansible.builtin.systemd_service:
        name: rsyslog
        state: restarted
        enabled: true

- name: Install Backup Public SSH Key on VMs
  hosts: vms
  become: true
  tasks:
    - name: Add Public Key to authorized_keys
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', 'roles/backup/files/id_rsa.pub') }}"

- name: Install Backup Public SSH Key
  hosts: vms
  become: true
  tasks:
    - name: Add Public Key to authorized_keys on VMs
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', 'roles/backup/files/id_rsa.pub') }}"

    - name: Add backup server key to Hetzner Storage Box using ssh-copy-id
      become: false
      ansible.builtin.shell: >
        ssh-copy-id
        -s
        -i roles/backup/files/id_rsa.pub
        -o IdentityFile=/home/ehopkins/.ssh/id_ed25519
        -o Port=23
        u456419@u456419.your-storagebox.de
      delegate_to: localhost
      run_once: true
      # noqa no-changed-when run-once

- name: Start Docker Compose Stacks
  hosts: docker
  become: true
  tasks:
    - name: Start Docker Compose Stacks in all VMs
      community.docker.docker_compose_v2:
        project_src: /home/{{ ansible_user }}
        state: present

- name: Turn Off SSH PasswordAuthentication
  hosts: all
  become: true
  tasks:
    - name: Ensure PasswordAuthentication is disabled
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication\s+'
        line: 'PasswordAuthentication no'
        state: present

    - name: Ensure PermitRootLogin is key-based only
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin\s+'
        line: 'PermitRootLogin prohibit-password'
        state: present

    - name: Restart SSH service to apply changes
      ansible.builtin.service:
        name: sshd
        state: restarted
