- name: Become Block
  become: true
  block:
    - name: Create Directory Structure
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/samba"
        state: directory
        mode: "0755"
        owner: 1000
        group: 994

    - name: Render Docker Compose
      ansible.builtin.template:
        src: "docker-compose.yml.j2"
        dest: "/home/{{ ansible_user }}/docker-compose.yml"
        force: true
        mode: "0664"
        owner: "{{ ansible_user }}"
        group: 994
