services:
  budget:
    image: docker.io/actualbudget/actual-server:latest
    container_name: budget
    environment:
      - ACTUAL_HTTPS_KEY=/data/selfhost.key
      - ACTUAL_HTTPS_CERT=/data/selfhost.crt
      - PUID=1000
      - PGID=994
      - TZ=America/New_York
    ports:
      - '5006:5006'
    volumes:
      - ./actual:/data
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - PUID=1000
      - PGID=994
      - TZ=America/New_York
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped