- name: Become Block
  become: true
  block:
    - name: Create NC Directory Structure
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
        owner: 33
        group: 33
      loop:
        - "/home/{{ ansible_user }}/nextcloud/html/config"

    - name: Create Redis Directory Structure
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
        owner: 999
        group: 994
      loop:
        - "/home/{{ ansible_user }}/nextcloud/cache"

    - name: Copy NextCloud Dockerfile
      ansible.builtin.copy:
        src: "Dockerfile"
        dest: "/home/{{ ansible_user }}/Dockerfile"
        mode: "0664"
        owner: "{{ ansible_user }}"
        group: 994

    - name: Render Docker Compose
      ansible.builtin.template:
        src: "docker-compose.yml.j2"
        dest: "/home/{{ ansible_user }}/docker-compose.yml"
        force: true
        mode: "0664"
        owner: "{{ ansible_user }}"
        group: 994

    - name: Render NextCloud Config
      ansible.builtin.template:
        src: "config.php.j2"
        dest: "/home/{{ ansible_user }}/nextcloud/html/config/config.php"
        force: true
        mode: "0664"
        owner: 33
        group: 33
