galaxy_info:
  author: Eli Hopkins
  description: Deploy NextCloud Stack
  license: ""
  min_ansible_version: ""
  platforms: []

  galaxy_tags:
    - nextcloud
    - files
    - office

dependencies:
  - role: vm
  - role: docker
