- name: Become Block
  become: true
  block:
    - name: Create Data Folder
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
        owner: "{{ ansible_user }}"
        group: 994
      loop:
        - "/home/{{ ansible_user }}/search"

    - name: Copy Docker Compose
      ansible.builtin.copy:
        src: "docker-compose.yml"
        dest: "/home/{{ ansible_user }}/docker-compose.yml"
        mode: "0664"
        owner: "{{ ansible_user }}"
        group: 994

    - name: Render Config
      ansible.builtin.template:
        src: "settings.yml.j2"
        dest: "/home/{{ ansible_user }}/search/config/settings.yml"
        force: true
        mode: "0664"
        owner: "{{ ansible_user }}"
        group: 994
