- name: Render Docker Compose Template
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "/home/{{ ansible_user }}/docker-compose.yml"
    mode: "0664"
    owner: 1000
    group: 994
