- name: Include cadvisor with variables
  ansible.builtin.include_role:
    name: prometheus.prometheus.cadvisor
  vars:
    cadvisor_port: 8085

- name: Become Block
  become: true
  block:
    - name: Ensure ca-certificates and curl are installed
      ansible.builtin.apt:
        name:
          - ca-certificates
        state: present

    - name: Ensure /etc/apt/keyrings exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"
        owner: "root"
        group: "root"

    - name: Download Docker GPG key to /etc/apt/keyrings/docker.asc
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"
        owner: root
        group: root

    - name: Add Docker apt repository
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: |
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable
        mode: "0644"

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Add User to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        group: docker

- name: Create Alloy Compose
  when: inventory_hostname != "monitor"
  block:
    - name: Create Alloy Directory
      ansible.builtin.file:
        path: "/home/{{ ansible_user }}/alloy"
        state: directory
        mode: "0755"
        owner: "{{ ansible_user }}"
        group: 994

    - name: Copy Docker Compose
      ansible.builtin.copy:
        src: "docker-compose.yml"
        dest: "/home/{{ ansible_user }}/alloy/docker-compose.yml"
        mode: "0664"
        owner: 1000
        group: 994

    - name: Render Alloy Config
      ansible.builtin.template:
        src: "config.alloy.j2"
        dest: "/home/{{ ansible_user }}/alloy/config.alloy"
        mode: "0664"
        owner: 1000
        group: 994

    - name: Start Docker Compose
      community.docker.docker_compose_v2:
        project_src: /home/{{ ansible_user }}/alloy
        state: present
